import type { Metadata } from "next";
import { Zen_Kaku_Gothic_New, Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const zenKakuGothicNew = Zen_Kaku_Gothic_New({
  weight: ["500", "700"],
  subsets: ["latin"],
  variable: "--tn-font-base",
});
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--tn-font-sub",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${zenKakuGothicNew.variable} ${outfit.variable} ` }
    >
      <body className="tracking-wider font-medium font-base text-sm lg:text-base">
        <div className="overflow-hidden ">
        <Header />
        {children}
        </div>
      </body>
    </html>
  );
}
